version: '3.2'


services: 

  currency-conversion-service:
    image: currency-conversion-service-image
    ports:
      - "8100:8100"
    environment:
      - CURRENCY_EXCHANGE_ENDPOINT=http://currency-exchange-service:8001
    deploy:
       replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

 currency-exchange-service:
    
    image: currency-exchange-service-image
    ports:
      - "8001:8001"
    deploy:
       replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      endpoint_mode: vip