version: '3.2'


services: 

  currency-conversion-service:
    image: saxenankit/currency-conversion-service-image:1.0
    ports:
      - "8100:8100"
    environment:
      - CURRENCY_EXCHANGE_ENDPOINT=http://currency-exchange-service:8001
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

 
