FROM openjdk:8u151-jdk-alpine

WORKDIR $(pwd)/currency-conversion-service/target

COPY currency-conversion-service-0.0.1-SNAPSHOT.jar /usr/data/currency-conversion-service-1.0.jar

EXPOSE 8100

CMD java -jar currency-conversion-service-1.0.jar