FROM openjdk:8u151-jdk-alpine


COPY /target/currency-conversion-service-0.0.1-SNAPSHOT.jar /usr/data/currency-conversion-service-1.0.jar

WORKDIR /usr/data

EXPOSE 8100

CMD java -jar currency-conversion-service-1.0.jar
